In [363]:
import requests
from bs4 import BeautifulSoup
from IPython.core.display import display, HTML

In [364]:
#url = "https://factfinder.census.gov/faces/tableservices/jsf/pages/productview.xhtml?src=bkmk"
url = "http://www.gopsusports.com/sports/m-basebl/stats/2017-2018/teamcume.html"
result = requests.get(url)
print(result.status_code)

200

In [365]:
html = result.text

In [366]:
soup = BeautifulSoup(html, 'html.parser')

In [367]:
print(soup.prettify())

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
 <body>
  <!--<img src="http://grfx.cstv.com/schools/utah/graphics/spacer.gif" width=1 height=10><br> -->
  <span class="storyheadline">
  </span>
  <br/>
  <img height="10" src="http://grfx.cstv.com/schools/utah/graphics/spacer.gif" width="1"/>
  <br/>
  <!-- DO NOT EDIT BELOW THIS LINE -->
  <!-- DO NOT EDIT ABOVE THIS LINE -->
  <center>
   <h2>
    <font face="verdana">
     Penn State
    </font>
   </h2>
   <b>
    Season Statistics
   </b>
  </center>
  <center>
   <center>
    <ul>
     <li>
      <a href="#TEAM.MLB">
       <font face="verdana" size="2">
        Overall Statistics
       </font>
      </a>
     </li>
     <li>
      <a href="#TEAM.GMS">
       <font face="verdana" size="2">
        Games Summary
       </font>
      </a>
     </li>
    </ul>
   </center>
   <!--File source:C:\TASBS\2018\reports\TEAM.MLB-->
   <a name="TEAM.MLB">
   </a>
   <font face="verdana">
    <center>
     <table border="0" width="100%">
      <!--t-lgx-->
      <tr bgcolor="#c0c0c0">
       <td>
        <center>
         <b>
          Overall Statistics
         </b>
        </center>
       </td>
      </tr>
     </table>
     <!--t-lgx-->
     <br/>
     <font face="verdana" size="2">
       Record: 4-8  Home: 0-1  Away: 4-4  Neutral: 0-3  Big Ten: 0-0 
     </font>
     <p>
      <table border="0" cellpadding="2" cellspacing="0">
       <tr bgcolor="#00008b">
        <td align="left" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           Player
          </b>
         </font>
        </td>
        <td align="right" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           avg
          </b>
         </font>
        </td>
        <td align="center" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           gp-gs
          </b>
         </font>
        </td>
        <td align="right" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           ab
          </b>
         </font>
        </td>
        <td align="right" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           r
          </b>
         </font>
        </td>
        <td align="right" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           h
          </b>
         </font>
        </td>
        <td align="right" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           2b
          </b>
         </font>
        </td>
        <td align="right" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           3b
          </b>
         </font>
        </td>
        <td align="right" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           hr
          </b>
         </font>
        </td>
        <td align="right" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           rbi
          </b>
         </font>
        </td>
        <td align="right" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           tb
          </b>
         </font>
        </td>
        <td align="right" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           slg%
          </b>
         </font>
        </td>
        <td align="right" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           bb
          </b>
         </font>
        </td>
        <td align="right" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           hbp
          </b>
         </font>
        </td>
        <td align="right" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           so
          </b>
         </font>
        </td>
        <td align="right" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           gdp
          </b>
         </font>
        </td>
        <td align="right" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           ob%
          </b>
         </font>
        </td>
        <td align="right" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           sf
          </b>
         </font>
        </td>
        <td align="right" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           sh
          </b>
         </font>
        </td>
        <td align="center" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           sb-att
          </b>
         </font>
        </td>
        <td align="right" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           po
          </b>
         </font>
        </td>
        <td align="right" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           a
          </b>
         </font>
        </td>
        <td align="right" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           e
          </b>
         </font>
        </td>
        <td align="right" bgcolor="#00008b">
         <font color="#ffffff" face="verdana" size="1">
          <b>
           fld%
          </b>
         </font>
        </td>
       </tr>
       <tr bgcolor="#ffffff">
        <td align="left">
         <font color="#000000" face="verdana" size="1">
          <a href="http://www.gopsusports.com/sports/m-basebl/mtt/ryan_sloniger_983608.html" target="_new">
           Sloniger, Ryan
          </a>
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          .302
         </font>
        </td>
        <td align="center">
         <font color="#000000" face="verdana" size="1">
          12-12
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          43
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          6
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          13
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          3
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          2
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          13
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          22
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          .512
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          10
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          12
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          .434
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="center">
         <font color="#000000" face="verdana" size="1">
          1-2
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          96
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          7
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          1.000
         </font>
        </td>
       </tr>
       <tr bgcolor="#ffffff">
        <td align="left">
         <font color="#000000" face="verdana" size="1">
          <a href="http://www.gopsusports.com/sports/m-basebl/mtt/braxton_giavedoni_1026251.html" target="_new">
           Giavedoni, Braxton
          </a>
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          .288
         </font>
        </td>
        <td align="center">
         <font color="#000000" face="verdana" size="1">
          12-12
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          52
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          7
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          15
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          1
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          2
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          4
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          22
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          .423
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          1
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          19
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          1
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          .296
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          1
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="center">
         <font color="#000000" face="verdana" size="1">
          2-3
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          19
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          1
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          .950
         </font>
        </td>
       </tr>
       <tr bgcolor="#ffffff">
        <td align="left">
         <font color="#000000" face="verdana" size="1">
          <a href="http://www.gopsusports.com/sports/m-basebl/mtt/jordan_bowersox_983629.html" target="_new">
           Bowersox, Jordan
          </a>
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          .286
         </font>
        </td>
        <td align="center">
         <font color="#000000" face="verdana" size="1">
          12-12
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          49
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          9
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          14
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          4
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          8
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          18
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          .367
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          2
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          2
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          14
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          .333
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          1
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          1
         </font>
        </td>
        <td align="center">
         <font color="#000000" face="verdana" size="1">
          2-2
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          33
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          1.000
         </font>
        </td>
       </tr>
       <tr bgcolor="#ffffff">
        <td align="left">
         <font color="#000000" face="verdana" size="1">
          <a href="http://www.gopsusports.com/sports/m-basebl/mtt/connor_klemann_983627.html" target="_new">
           Klemann, Connor
          </a>
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          .277
         </font>
        </td>
        <td align="center">
         <font color="#000000" face="verdana" size="1">
          12-12
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          47
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          4
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          13
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          2
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          2
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          8
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          21
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          .447
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          7
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          1
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          15
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          .382
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="center">
         <font color="#000000" face="verdana" size="1">
          2-2
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          13
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          2
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          .867
         </font>
        </td>
       </tr>
       <tr bgcolor="#ffffff">
        <td align="left">
         <font color="#000000" face="verdana" size="1">
          <a href="http://www.gopsusports.com/sports/m-basebl/mtt/shea_sbranti_1059633.html" target="_new">
           Sbranti, Shea
          </a>
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          .214
         </font>
        </td>
        <td align="center">
         <font color="#000000" face="verdana" size="1">
          8-8
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          28
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          3
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          6
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="right">
         <font color="#000000" face="verdana" size="1">
          0
         </font>
        </td>
        <td align="right">

In [368]:
p = soup.find(name='p')
table = p.find('table')
print(table.text)

Player
avg
gp-gs
ab
r
h
2b
3b
hr
rbi
tb
slg%
bb
hbp
so
gdp
ob%
sf
sh
sb-att
po
a
e
fld%


Sloniger, Ryan
 .302
12-12
43
6
13
3
0
2
13
22
 .512
10
0
12
0
 .434
0
0
1-2
96
7
0
1.000


Giavedoni, Braxton
 .288
12-12
52
7
15
1
0
2
4
22
 .423
1
0
19
1
 .296
1
0
2-3
19
0
1
 .950


Bowersox, Jordan
 .286
12-12
49
9
14
4
0
0
8
18
 .367
2
2
14
0
 .333
1
1
2-2
33
0
0
1.000


Klemann, Connor
 .277
12-12
47
4
13
2
0
2
8
21
 .447
7
1
15
0
 .382
0
0
2-2
0
13
2
 .867


Sbranti, Shea
 .214
8-8
28
3
6
0
0
0
3
6
 .214
5
3
11
0
 .389
0
1
0-0
60
4
0
1.000


Gibson, Tommy
 .212
11-10
33
8
7
1
0
0
2
8
 .242
4
3
13
0
 .350
0
0
0-0
13
29
6
 .875


Nadeau, Mason
 .176
11-9
34
5
6
0
1
0
2
8
 .235
7
0
13
0
 .317
0
0
2-2
17
0
1
 .944


Hughes, Conlin
 .111
12-11
36
2
4
1
1
0
2
7
 .194
6
1
6
0
 .256
0
1
2-3
21
32
0
1.000

----------

Hendershot, Parker
 .429
5-3
14
2
6
1
0
0
2
7
 .500
0
0
6
0
 .429
0
0
0-0
0
0
0
 .000


Weisenseel, Joe
 .167
5-2
12
1
2
2
0
0
1
4
 .333
0
0
3
0
 .167
0
0
0-0
4
4
0
1.000


Goodnight, Logan
 .150
9-6
20
2
3
1
0
1
3
7
 .350
2
1
13
0
 .261
0
0
0-0
2
8
2
 .833


Robison, Curtis
 .148
9-7
27
3
4
1
0
1
2
8
 .296
5
0
8
0
 .281
0
0
2-2
29
2
0
1.000


Orndorff, Derek
 .143
5-1
7
0
1
0
1
0
0
3
 .429
1
0
6
0
 .250
0
0
0-0
9
0
0
1.000


Hippenhammer, Mac
 .100
5-3
10
1
1
0
0
0
0
1
 .100
0
0
4
0
 .100
0
0
0-0
7
0
0
1.000


Riggins, Austin
 .000
2-0
5
0
0
0
0
0
0
0
 .000
0
0
4
0
 .000
0
0
0-0
1
0
0
1.000


Kremer, Kris
 .000
2-0
1
0
0
0
0
0
0
0
 .000
1
0
1
0
 .500
0
0
0-0
0
0
0
 .000


Totals
 .227
12-12
418
53
95
17
3
8
50
142
 .340
51
11
148
1
 .326
2
3
13-16
316
114
13
 .971


Opponents
 .277
12-12
423
83
117
25
2
8
77
170
 .402
57
9
98
6
 .372
3
6
11-15
330
85
11
 .974

In [369]:
keys = []
for row in table.findAll(name='tr')[0:1]:
    for key in row.findAll(name='td')[1:]:
        keys.append(key.text.encode('ascii','ignore'))
print(keys)

['avg', 'gp-gs', 'ab', 'r', 'h', '2b', '3b', 'hr', 'rbi', 'tb', 'slg%', 'bb', 'hbp', 'so', 'gdp', 'ob%', 'sf', 'sh', 'sb-att', 'po', 'a', 'e', 'fld%']

In [370]:
dictionary = {}
for rows in table.findAll(name='tr')[1:]:
    #print(rows)
    #print('**************')
    if rows.name == 'tr':
        try:
            i = 0
            player = str(rows.find('a').text.encode('ascii'))
            dictionary[player] = {}
            for column in rows.findAll('td')[1:]:
                key = str(keys[i])
                dictionary[player][key] = str(column.text.encode('ascii','ignore'))
                i = i+1
        except: 
            pass

In [371]:
print(dictionary)

{'Hughes, Conlin': {'gdp': '0', 'ab': '36', 'avg': ' .111', 'fld%': '1.000', 'ob%': ' .256', 'sb-att': '2-3', '3b': '1', 'tb': '7', 'po': '21', '2b': '1', 'bb': '6', 'hr': '0', 'slg%': ' .194', 'r': '2', 'a': '32', 'e': '0', 'h': '4', 'hbp': '1', 'sh': '1', 'so': '6', 'gp-gs': '12-11', 'rbi': '2', 'sf': '0'}, 'Bowersox, Jordan': {'gdp': '0', 'ab': '49', 'avg': ' .286', 'fld%': '1.000', 'ob%': ' .333', 'sb-att': '2-2', '3b': '0', 'tb': '18', 'po': '33', '2b': '4', 'bb': '2', 'hr': '0', 'slg%': ' .367', 'r': '9', 'a': '0', 'e': '0', 'h': '14', 'hbp': '2', 'sh': '1', 'so': '14', 'gp-gs': '12-12', 'rbi': '8', 'sf': '1'}, 'Hippenhammer, Mac': {'gdp': '0', 'ab': '10', 'avg': ' .100', 'fld%': '1.000', 'ob%': ' .100', 'sb-att': '0-0', '3b': '0', 'tb': '1', 'po': '7', '2b': '0', 'bb': '0', 'hr': '0', 'slg%': ' .100', 'r': '1', 'a': '0', 'e': '0', 'h': '1', 'hbp': '0', 'sh': '0', 'so': '4', 'gp-gs': '5-3', 'rbi': '0', 'sf': '0'}, 'Sloniger, Ryan': {'gdp': '0', 'ab': '43', 'avg': ' .302', 'fld%': '1.000', 'ob%': ' .434', 'sb-att': '1-2', '3b': '0', 'tb': '22', 'po': '96', '2b': '3', 'bb': '10', 'hr': '2', 'slg%': ' .512', 'r': '6', 'a': '7', 'e': '0', 'h': '13', 'hbp': '0', 'sh': '0', 'so': '12', 'gp-gs': '12-12', 'rbi': '13', 'sf': '0'}, 'Sbranti, Shea': {'gdp': '0', 'ab': '28', 'avg': ' .214', 'fld%': '1.000', 'ob%': ' .389', 'sb-att': '0-0', '3b': '0', 'tb': '6', 'po': '60', '2b': '0', 'bb': '5', 'hr': '0', 'slg%': ' .214', 'r': '3', 'a': '4', 'e': '0', 'h': '6', 'hbp': '3', 'sh': '1', 'so': '11', 'gp-gs': '8-8', 'rbi': '3', 'sf': '0'}, 'Goodnight, Logan': {'gdp': '0', 'ab': '20', 'avg': ' .150', 'fld%': ' .833', 'ob%': ' .261', 'sb-att': '0-0', '3b': '0', 'tb': '7', 'po': '2', '2b': '1', 'bb': '2', 'hr': '1', 'slg%': ' .350', 'r': '2', 'a': '8', 'e': '2', 'h': '3', 'hbp': '1', 'sh': '0', 'so': '13', 'gp-gs': '9-6', 'rbi': '3', 'sf': '0'}, 'Weisenseel, Joe': {'gdp': '0', 'ab': '12', 'avg': ' .167', 'fld%': '1.000', 'ob%': ' .167', 'sb-att': '0-0', '3b': '0', 'tb': '4', 'po': '4', '2b': '2', 'bb': '0', 'hr': '0', 'slg%': ' .333', 'r': '1', 'a': '4', 'e': '0', 'h': '2', 'hbp': '0', 'sh': '0', 'so': '3', 'gp-gs': '5-2', 'rbi': '1', 'sf': '0'}, 'Kremer, Kris': {'gdp': '0', 'ab': '1', 'avg': ' .000', 'fld%': ' .000', 'ob%': ' .500', 'sb-att': '0-0', '3b': '0', 'tb': '0', 'po': '0', '2b': '0', 'bb': '1', 'hr': '0', 'slg%': ' .000', 'r': '0', 'a': '0', 'e': '0', 'h': '0', 'hbp': '0', 'sh': '0', 'so': '1', 'gp-gs': '2-0', 'rbi': '0', 'sf': '0'}, 'Giavedoni, Braxton': {'gdp': '1', 'ab': '52', 'avg': ' .288', 'fld%': ' .950', 'ob%': ' .296', 'sb-att': '2-3', '3b': '0', 'tb': '22', 'po': '19', '2b': '1', 'bb': '1', 'hr': '2', 'slg%': ' .423', 'r': '7', 'a': '0', 'e': '1', 'h': '15', 'hbp': '0', 'sh': '0', 'so': '19', 'gp-gs': '12-12', 'rbi': '4', 'sf': '1'}, 'Riggins, Austin': {'gdp': '0', 'ab': '5', 'avg': ' .000', 'fld%': '1.000', 'ob%': ' .000', 'sb-att': '0-0', '3b': '0', 'tb': '0', 'po': '1', '2b': '0', 'bb': '0', 'hr': '0', 'slg%': ' .000', 'r': '0', 'a': '0', 'e': '0', 'h': '0', 'hbp': '0', 'sh': '0', 'so': '4', 'gp-gs': '2-0', 'rbi': '0', 'sf': '0'}, 'Robison, Curtis': {'gdp': '0', 'ab': '27', 'avg': ' .148', 'fld%': '1.000', 'ob%': ' .281', 'sb-att': '2-2', '3b': '0', 'tb': '8', 'po': '29', '2b': '1', 'bb': '5', 'hr': '1', 'slg%': ' .296', 'r': '3', 'a': '2', 'e': '0', 'h': '4', 'hbp': '0', 'sh': '0', 'so': '8', 'gp-gs': '9-7', 'rbi': '2', 'sf': '0'}, 'Orndorff, Derek': {'gdp': '0', 'ab': '7', 'avg': ' .143', 'fld%': '1.000', 'ob%': ' .250', 'sb-att': '0-0', '3b': '1', 'tb': '3', 'po': '9', '2b': '0', 'bb': '1', 'hr': '0', 'slg%': ' .429', 'r': '0', 'a': '0', 'e': '0', 'h': '1', 'hbp': '0', 'sh': '0', 'so': '6', 'gp-gs': '5-1', 'rbi': '0', 'sf': '0'}, 'Nadeau, Mason': {'gdp': '0', 'ab': '34', 'avg': ' .176', 'fld%': ' .944', 'ob%': ' .317', 'sb-att': '2-2', '3b': '1', 'tb': '8', 'po': '17', '2b': '0', 'bb': '7', 'hr': '0', 'slg%': ' .235', 'r': '5', 'a': '0', 'e': '1', 'h': '6', 'hbp': '0', 'sh': '0', 'so': '13', 'gp-gs': '11-9', 'rbi': '2', 'sf': '0'}, 'Gibson, Tommy': {'gdp': '0', 'ab': '33', 'avg': ' .212', 'fld%': ' .875', 'ob%': ' .350', 'sb-att': '0-0', '3b': '0', 'tb': '8', 'po': '13', '2b': '1', 'bb': '4', 'hr': '0', 'slg%': ' .242', 'r': '8', 'a': '29', 'e': '6', 'h': '7', 'hbp': '3', 'sh': '0', 'so': '13', 'gp-gs': '11-10', 'rbi': '2', 'sf': '0'}, 'Klemann, Connor': {'gdp': '0', 'ab': '47', 'avg': ' .277', 'fld%': ' .867', 'ob%': ' .382', 'sb-att': '2-2', '3b': '0', 'tb': '21', 'po': '0', '2b': '2', 'bb': '7', 'hr': '2', 'slg%': ' .447', 'r': '4', 'a': '13', 'e': '2', 'h': '13', 'hbp': '1', 'sh': '0', 'so': '15', 'gp-gs': '12-12', 'rbi': '8', 'sf': '0'}, 'Hendershot, Parker': {'gdp': '0', 'ab': '14', 'avg': ' .429', 'fld%': ' .000', 'ob%': ' .429', 'sb-att': '0-0', '3b': '0', 'tb': '7', 'po': '0', '2b': '1', 'bb': '0', 'hr': '0', 'slg%': ' .500', 'r': '2', 'a': '0', 'e': '0', 'h': '6', 'hbp': '0', 'sh': '0', 'so': '6', 'gp-gs': '5-3', 'rbi': '2', 'sf': '0'}}